sonar.projectKey=LmarDark_expert-bassoon_b756caf5-729e-4ad8-8b3b-b954a72a4829
sonar.projectName=expert-bassoon
sonar.projectVersion=1.0

# Diretórios de código-fonte
sonar.sources=app,resources/js
sonar.tests=tests

# Codificação
sonar.sourceEncoding=UTF-8

# Exclusões gerais (vendor, node_modules, assets compilados)
sonar.exclusions=\
  vendor/**,\
  node_modules/**,\
  public/build/**,\
  storage/**,\
  bootstrap/cache/**

# Exclusões de cobertura
sonar.coverage.exclusions=\
  database/migrations/**,\
  bootstrap/app.php,\
  routes/web.php,\
  app/Http/Requests/**,\
  tests/**,\
  resources/js/**

# Relatório de cobertura PHP (formato Clover gerado pelo Pest/PHPUnit)
sonar.php.coverage.reportPaths=coverage.xml

# Linguagens
sonar.language=php
